### ISSUE TITLE
Overloaded Livery Select Options when Adding New Aircraft to Fleet

### ISSUE THREAD

**Issue by IFHappyDays** [VACenter/VACenter#108]
**Describe the bug**
When selecting a livery for an aircraft when adding an new aircraft to the fleet, many duplicates of the same options appear, and increase in number as more aircraft are added.

**To Reproduce**
1. Go to the 'Admin' Tab
2. Click on 'Aircraft'
3. Click on 'Add Aircraft'
4. Select any aircraft
5. Expand the drop down menu for aircraft liveries
6. Error will be evident, many duplicates of the same livery present

**Expected behavior**
One livery option present only.

**Screenshots**
![image](https://user-images.githubusercontent.com/105061088/167149904-808d44ac-e9ce-47b5-82ab-4303792b2286.png)

**Desktop:**
 - OS: Windows 11 21H2
 - Browser: Firefox
 - Version 100.0 (64-bit) 

**Smartphone:**
- OS: One UI 3.1
- Browser: Stock Samsung Browser
- Version 17.0.1.69

**Additional context**
This error is evident for all aircraft, and reproduces on both smartphone and desktop versions of the website.

**Comment by Sam-Neale** [comment]
This issue is no longer relevant as v3.2 is now no longer supported.
