### ISSUE TITLE
Ability to revoke access from the last/only user.

### ISSUE THREAD

**Issue by teddy9264** [VACenter/VACenter#16]
You can revoke access to VACenter to the last admin account and be locked out of the server unless you change the user files to regain access.

**Comment by Sam-Neale** [comment]
@teddy9264 please test the fix in commit cceae9215342ab363ddf4ac9b631bd58b8c3d49e

**Comment by teddy9264** [comment]
The commit did not resolve the issue.

**Comment by Sam-Neale** [comment]
@teddy9264 please test fix in commit 32a613f

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by teddy9264** [comment]
The commit did not resolve the issue.

**Comment by Sam-Neale** [comment]
@teddy9264 please test fix in 23ac10ad1ab647d4e895beebdf84ad38ad307bb3

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sam-Neale** [comment]
Resolved in 61ef11a4ab4c9a0e09d79466fab5275b0430b954
