### ISSUE TITLE
Suggestion: VANet for app

### ISSUE THREAD

**Issue by dylandavis499** [VACenter/VACenter#17]
@Sam-Neale, @teddy9264

I should like to make a suggestion for iPhone, iPad, Android, MacBook, and Windows can add access for VANet app like VA Crew Center to login in, and add feature for switch accounts for Crew Center for Virtual Airlines. Let me know, if you like to make a new feature for VANet Crew Center on apps.

Thank you,
Dylan Davis.

**Comment by SamuelSamouris** [comment]
Thanks for the suggestion we'll look into its implimentation

**Comment by dylandavis499** [comment]
Great, sound good! Let me know, what you doing on new enhancement! :)

**Comment by Sam-Neale** [comment]
Discussed issue, and decided to not move forward.
