### ISSUE TITLE
/admin/users PIREPs table: Data is hidden when screen width is small, no clear way to navigate.

### ISSUE THREAD

**Issue by nic-hanna** [VACenter/VACenter#94]
**Describe the bug**
When navigating to /admin/users, the PIREP table, when empty, displays "No matching records found", when the window is 50% of a 16:9 display the data is cut off and no clear way of scrolling.

![image](https://user-images.githubusercontent.com/45321696/147332419-5a3728ce-6d0a-45b8-998f-4f5f4c9d0986.png)

**Comment by Sam-Neale** [comment]
You can scroll...
